import Head from 'next/head';
import { Inter } from 'next/font/google';
import ContentService from '../utils/content-service';
import { GetStaticProps, NextPage } from 'next';
import { IProjectFields } from '@/@types/generated/contentful';

const inter = Inter({ subsets: ['latin'] });

interface HomeProps {
  projects: IProjectFields[];
}

const Home: NextPage<HomeProps> = ({ projects }) => {
  return (
    <>
      <Head>
        <title>Mi2sDesign</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center">
        <h1 className="text-2xl mt-6">Mi2sDesign</h1>
        <ul className="flex flex-col space-y-2 items-center justify-center mt-10">
          {projects.map((project) => {
            return <li key={project.id}>{project.title}</li>;
          })}
        </ul>
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const projects = (
    await ContentService.instance.getEntriesByType<IProjectFields>('project')
  ).map((entry) => entry.fields);

  return {
    props: {
      projects,
    },
    revalidate: 1,
  };
};
